filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true  # Включаем подсказки для обнаружения Docker-контейнеров

# Определяем общие настройки для всех контейнеров
filebeat.inputs:
  - type: filestream
    id: system-logs
    paths:
      - /var/log/*.log
    fields:
      log_type: system  # Добавьте пользовательское поле для идентификации
      data_stream.type: logs
      data_stream.dataset: system_log
      data_stream.namespace: default

    fields_under_root: true  # Поместите пользовательские поля на корень документа

setup.ilm.enabled: true 
setup.ilm.policy_name: "delete-after-30-days"
setup.ilm.check_exists: false
setup.template.enabled: false

processors:
  - add_docker_metadata: ~  # Добавляем метаданные Docker

setup.kibana:
  host: ${KIBANA_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}

output.elasticsearch:
  hosts: ${ELASTIC_HOSTS}
  username: ${ELASTIC_USER}
  password: ${ELASTIC_PASSWORD}
  ssl.enabled: true
  ssl.certificate_authorities: "certs/ca/ca.crt"

# Настройка индексов для разных типов логов
  indices:
    - index: "%{[data_stream.type]}-%{[data_stream.dataset]}-%{[data_stream.namespace]}"   # Индекс для системных логов
      when:
        contains:
          log_type: "system"  # Условие для системных логов

